[package]
name = "techtrend"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "7"
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
